#
# Perform OSX environment setup
#
---

- name: 'Check if Rosetta is Installed (M1)'
  stat:
    path: /Library/Apple/usr/share/rosetta/rosetta
  register: rosettafile
  when: ansible_machine == 'arm64'

- name: 'Status of Rosetta'
  debug:
    msg: "Rosetta file does not exist..."
  when: 
    - rosettafile is defined
    - not rosettafile.stat.exists

- name: 'Status of Rosetta'
  debug:
    msg: "Rosetta file exists"
  when: 
    - rosettafile is defined
    - rosettafile.stat.exists

- name: 'Install Rosetta 2'
  shell: 'softwareupdate --agree-to-license --install-rosetta'
  become: true
  when: 
    - rosettafile is defined
    - not rosettafile.stat.exists

# - name: 'Check if Rosetta is Installed (M1)'
#   file:
#     path: /Library/Apple/usr/share/rosetta/rosetta
#     owner: "{{ homebrew_user }}"
#     state: directory
#   become: true
#   when: ansible_machine == 'arm64'

# - name: 'Set Hostname'

