#
# Global variables to override all role variables & role defaults
#

# Local sudo
sudo_passwd: "{{ vault_sudo_passwd }}"
ansible_become_pass: "{{ vault_ansible_become_pass }}"

# Git
git_username: "{{ vault_git_username }}"
git_useremail: "{{ vault_git_useremail }}"

# Mac App Store
mas_email: "{{ vault_mas_email }}"
mas_password: "{{ vault_mas_password }}"

# OSX System Settings
my_hostname: ba-osx-macbook3

# Source location for Files
my_sourcefiles_homedir: /Volumes/data01/computing/ansible_sources_homedir
my_sourcefiles_homebin: /Volumes/data01/computing/ansible_sources_homebin

# Folders to Create
dirs_under_homedir: "{{ vault_dirs_under_homedir }}"
dirs_under_documents: "{{ vault_dirs_under_documents }}"

# Hashicorp Tools
hashicorp_binaries:
  - https://releases.hashicorp.com/vault/1.4.0/vault_1.4.0_darwin_amd64.zip
  - https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_darwin_arm64.zip
  - https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_darwin_arm64.zip

# App Store Apps to Uninstall
mas_uninstalled_apps:
  - { id: 497799835 } # Xcode (13.2.1)
  # - { id: 497799835, name: "Xcode (13.2.1)" }

# App Store Apps to Install
mas_installed_apps:
  - { id: 405843582, name: "Alfred" }

# Packages to Install with Homebrew
homebrew_installed_packages:
  - azure-cli
  - bash     # Adds Bash v5 in /usr/local/bin
  - clamav
  # - { name: clamav, install_options:"version=1.1.0" }
  - dockutil
  - exa
  - ffmpeg
  - gh
  - git-delta
  - jq
  - kubectl
  - mkdocs
  - nmap
  - node
  - pv
  - rpm
  - shellcheck
  - socat
  - tflint
  - tradingview
  - tree
  - wget
  # - vagrant
  - youtube-dl

# GUI Apps to Install with Homebrew
homebrew_cask_apps:
  - android-file-transfer
  - citrix-workspace
  - docker
  - fig
  - firefox
  - google-chrome
  - microsoft-office
  - microsoft-remote-desktop
  - microsoft-teams
  - opera
  - powershell
  - signal
  - slack
  # - { name: snagit, install_options:"debug,version=2022.2.0" }
  - snagit
  - spotify
  - sublime-text
  # - { name: virtualbox, install_options:"debug,appdir=/Applications" }
  - visual-studio-code
  - vlc
  - whatsapp
  - zoho-mail

# PIP Packages
pip_package_list:
  - wheel
  - hvac    # Hashicorp Vault module for Ansible
  - mkdocs-material
  - mkdocs-mermaid2-plugin
  - mkdocs-drawio-file
  - pywinrm
  - spotdl

dockitems_remove:
  - TV
  - Podcasts
  - 'App Store'
  - Keynote

dockitems_persist:
  - name: Messages
    path: "/Applications/Messages.app/"
  - name: Safari
    path: "/Applications/Safari.app/"
    pos: 3
  - name: iMovie
    path: "/Applications/iMovie.app/"
    pos: 8
  - name: Google Chrome
    path: "/Applications/Google Chrome.app/"
    pos: 10
  - name: Opera
    path: "/Applications/Opera.app/"
    pos: 11
  - name: Firefox
    path: "/Applications/Firefox.app/"
    pos: 12
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app/"
    pos: 13
  - name: Sublime Text
    path: "/Applications/Sublime Text.app/"
    pos: 14
  - name: Slack
    path: "/Applications/Slack.app/"
    pos: 15
  - name: Signal
    path: "/Applications/Signal.app/"
    pos: 16
  # - name: Zoho Mail
  #   path: "/Applications/Zoho Mail - Desktop.app/"
  #   pos: 17
  - name: Spotify
    path: "/Applications/Spotify.app/"
    pos: 18
  - name: Docker
    path: "/Applications/Docker.app/"
    pos: 19

npm_packages:
  - name: webpack
    state: present # present/absent/latest, default: present
    # version: "^2.6" # default: N/A
  - name: create-react-app
    state: present # present/absent/latest, default: present
    # version: "^2.6" # default: N/A
