#
# Perform bash/zsh shell environment setup
#
---

# Sync home dir files from folder or network location (use -e syncfiles=yes on command line)
- name: "Check if Homedir Source Files Exist at {{ my_sourcefiles_homedir }}"
  stat:
    path: "{{ my_sourcefiles_homedir }}"
  register: srcdir

- name: "Rsync Homedir Files from Sources Dir: {{ my_sourcefiles_homedir }}"
  synchronize:
    src: "{{ my_sourcefiles_homedir }}/"
    dest: "{{ home_dir_path }}"
  when: 
    - srcdir.stat.exists
    - syncfiles is defined

# Sync $HOME/bin files from folder or network location (use -e syncfiles=yes on command line)
- name: "Check if $HOME/bin Source Files Exist at {{ my_sourcefiles_homebin }}"
  stat:
    path: "{{ my_sourcefiles_homebin }}"
  register: srcdir

- name: "Rsync $HOME/bin Files from Sources Dir: {{ my_sourcefiles_homebin }}"
  synchronize:
    src: "{{ my_sourcefiles_homebin }}/"
    dest: "{{ home_dir_path }}/bin"
  when: 
    - srcdir.stat.exists
    - syncfiles is defined

# Git Config Settings
- name: 'Configure Git Username'
  command: "git config --global user.name \"{{ git_username }}\""   

- name: 'Configure Git Email'
  command: "git config --global user.email \"{{ git_useremail }}\""

# Create Folder Structure
- name: 'Create Directory Structure Under $HOME'
  file:
    path: "~/{{ item }}"
    state: directory
    mode: 0775
  loop: "{{ dirs_under_homedir }}"

- name: 'Create Directory Structure Under ~/Documents'
  file:
    path: "~/Documents/{{ item }}"
    state: directory
    mode: 0775
  loop: "{{ dirs_under_documents }}"

# Download Hashicorp Tools
- name: 'Download Hashicorp Tool Binaries'
  get_url: 
    url: "{{ item }}"
    dest: ~/bin
  loop: "{{ hashicorp_binaries }}"

- name: 'Unzip Hashicorp Tool Binaries'
  unarchive: 
    src: "~/bin/{{ item }}"
    dest: ~/bin
  loop: "{{ hashicorp_binaries | map('basename') | list }}"

- name: 'Remove Hashicorp Zip Files'
  file:
    path: "~/bin/{{ item }}"
    state: absent
  loop: "{{ hashicorp_binaries | map('basename') | list }}"

# Create Link for Visual Studio Code Binary
- name: 'Create Link to VSCode Binary'
  file:
    src: '/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code'
    dest: "{{ home_dir_path }}/bin/code"
    state: link