#
# Perform bash/zsh shell environment setup
#
---

# - name: 'Set Hostname'

# - name: 'Create Directory Structure'

- name: 'Copy File: .zshrc'
  copy:
    src: .zshrc
    dest: "{{ home_dir_path }}/.zshrc"
    mode: '0644'

# - name: 'Ensure File is Present .zshrc'
#   file:
#     path: "{{ home_dir_path }}/.zshrc"
#     state: present
#     mode: 0644

- name: 'Configure Git Username'
  command: "git config --global user.name \"{{ git_username }}\""   

- name: 'Configure Git Email'
  command: "git config --global user.email \"{{ git_useremail }}\""

- name: 'Create Directory Structure Under $HOME'
  file:
    path: "~/{{ item }}"
    state: directory
    mode: 0775
  loop: "{{ dirs_under_homedir }}"

- name: 'Create Directory Structure Under ~/Documents'
  file:
    path: "~/Documents/{{ item }}"
    state: directory
    mode: 0775
  loop: "{{ dirs_under_documents }}"